############################
# STEP 1 build executable binary
############################
FROM golang:1.12.5-alpine3.9 as build-env
# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git \
    gcc \
    curl \
    pkgconf \
    libc-dev \
    librdkafka --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
    musl-dev \
    librdkafka-dev 
RUN mkdir /srv/messenger

WORKDIR /srv/messenger

# <- COPY go.mod and go.sum files to the workspace

COPY go.mod . 

COPY go.sum .

ENV GO111MODULE=on

RUN go mod download

COPY . .
# Fetch dependencies.
# Using go get.
RUN go build -o /go/bin/messenger ./cmd
# RUN go get -d -v
# Using go mod.
# RUN go mod download
# Build the binary.
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /go/bin/messenger
############################
# STEP 2 build a small image
############################
FROM scratch
COPY --from=build-env /go/bin/messenger /go/bin/messenger
ENTRYPOINT ["/go/bin/messenger"]