FROM golang:1.12.5-alpine3.9

RUN apk update && apk add --no-cache git \
    gcc \
    curl \
    pkgconfig \
    libc-dev \
    librdkafka --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
    musl-dev \
    librdkafka-dev

RUN mkdir /srv/messenger /tmp/key

RUN adduser -D -g '' appuser

WORKDIR /srv/messenger

COPY go.mod .

COPY go.sum .

ENV GO111MODULE=on

RUN go mod download

COPY . .

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -a -o /go/bin/messenger ./cmd

ENTRYPOINT ["/go/bin/messenger"]