version: "3.7"
services:
  pubsub-router:
    image: asia.gcr.io/solaire-resort-ops/real-time-event-processing/pubsub-router
    working_dir: /srv/messenger
    volumes: 
      - ./messenger:/srv/messenger
    command: tail -f /dev/null